### ISSUE TITLE
Hardware requirements for WIPP plugins

### ISSUE THREAD

**Issue by MyleneSimon** [usnistgov/WIPP#27]
**Description**
Some WIPP plugins may require specific hardware to run, for example a GPU with certain compute capabilities, or a certain CPU capability, see https://github.com/usnistgov/WIPP-backend/issues/109
In an heterogenous cluster, workflow pods may get scheduled on nodes that do not meet the plugin hardware requirements if these requirements are not taken into account.

**Proposal**
Add a new section in the plugin manifest for hardware requirements, for example:

```json
"hardwareRequirements": {
  "gpu": {
    "nvidia.com/gpu.compute.major": ">5"
  },
  "cpu": {
    "cpu-cpuid.AVX": "true"
  }
}
```
These requirements would then be translated into `nodeSelector` or `nodeAffinity`in the workflow step templates:
```yaml
nodeSelector:  
    feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
```
```yaml
affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "nvidia.com/gpu.compute.major"
                  operator: Gt
                  values: ["5"]
```

This relies on the auto-labeling of nodes using:
- https://github.com/kubernetes-sigs/node-feature-discovery
- https://github.com/NVIDIA/gpu-feature-discovery#generated-labels

One of the drawbacks in that if no nodes matching the node selectors are found, then the workflow step will hang indefinitely, unless we specify a timeout.

**Additional context**
See:
- https://github.com/kubernetes-sigs/node-feature-discovery
- https://github.com/NVIDIA/gpu-feature-discovery#generated-labels
- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

cc @Nicholas-Schaub @pbajcsy @sunnielyu this is open for discussion, any feedback regarding this approach, from the plugin manifest side of things and k8s side of things would be highly appreciated. I would like for us to agree on a format for the plugin manifest before starting the implementation in the backend.
